### PR TITLE
Create TEMPLATE.md

### PR DESCRIPTION
**Pull request by lerao**

### CODE REVIEW

**Comment by ghost** [comment]
https://startbootstrap.com/template/sb-admin

**Comment by LucenaNeto** [comment]
https://themewagon.com/themes/free-responsive-bootstrap-5-admin-template-material-dashboard-2/

https://themewagon.com/themes/free-bootstrap-4-html5-admin-dashboard-template-dashtreme/

**Comment by MarcosViniDLL** [comment]
https://themewagon.com/themes/free-responsive-bootstrap-5-html5-admin-template-sneat/

**Comment by AndersonSmuniz** [comment]
https://themefisher.com/products/novena-bootstrap

**Comment by wandersonlimaa** [comment]
https://startbootstrap.com/template/sb-admin-angular

**Comment by JasonCris4** [comment]
https://themewagon.com/themes/free-bootstrap-4-html-5-admin-dashboard-website-template-skydash/

**Comment by Anatarina20** [comment]
https://matrixadmin.wrappixel.com/

**Comment by Netodlima** [comment]
https://startbootstrap.com/template/heroic-features

**Comment by AdailtoJr** [comment]
https://themewagon.github.io/soffer/

**Comment by BarukFreitas** [comment]
https://www.free-css.com/free-css-templates/page296/klinik

**Comment by AdailtoJr** [comment]
https://themewagon.com/themes/soffer-responsive-free-bootstrap-5-html5-landing-page-template/

**Comment by lerao** [comment]
Escolhidos:
https://demos.themeselection.com/sneat-bootstrap-html-admin-template-free/html/index.html
https://demos.wrappixel.com/free-admin-templates/bootstrap/matrix-bootstrap-free/html/index.html

**Pull request closed without merging**
